#!/bin/bash
SCRIPT=$0
DIRNAME=`dirname $SCRIPT`
node - <<'JS' $DIRNAME $*
let [ SCRIPT, DASH, DIRNAME, ...args] = process.argv;
(async function() {
  const path = (await import('path'));
  const fs = (await import('fs'));
  const { promises: fsp } = fs;
  const { fileURLToPath } = (await import('url'));
  const srcPath = `${DIRNAME}/../src/inflections.csv`;

  let srcData = await fsp.readFile(srcPath);
  let srcLines = srcData.toString().trim().split('\n');
  let keys = srcLines[0].split(' , ');
  let inflections = [];

  for (let i=1; i<srcLines.length; i++) {
    let line = srcLines[i].split(' , ');
    let entry = {};
    for (let j=0; j<keys.length; j++) {
      let key = keys[j];
      let value = /\//.test(line[j]) ? line[j].split('/') : line[j];
      entry[key] = /---*/.test(value) ? null : value;
    }
    inflections.push(entry);
  }
  console.log(srcLines, keys, inflections);

  /*
  const { default:Dictionary } = (await import(
    `${DIRNAME}/../src/dictionary.mjs`));

  let dict =  await Dictionary.create();
  for (let i=0; i<args.length; i++) {
    let entry = args[i];
    let info = await dict.lookup(entry);
    console.log(entry);
    console.log(info);
  }
  */
})()
JS
