#!/usr/bin/bash
DBNAME=dpd.db
SCRIPT=`basename $0`
DPDDB='local/dpd.db'

if [[ ! -e "local/$DBNAME" ]]; then
  echo "$SCRIPT: [ERROR] missing $DBNAME"
  echo "$SCRIPT: [ERROR] run scripts/dpd-install"
  exit -1
fi;

# sqlite3 --batch local/dpd.db ".mode json" "select rowid rowid, id,lemma_1,lemma_2,pos,grammar,derived_from,neg,verb,trans,plus_case,meaning_1,meaning_lit,meaning_2,non_ia,sanskrit,root_key,root_sign,root_base,family_root,family_word,family_compound,family_idioms,family_set,derivative,suffix,phonetic,compound_type,compound_construction,non_root_in_comps,source_1,sutta_1,example_1,source_2,sutta_2,example_2,antonym,synonym,variant,var_phonetic,commentary,notes,cognate,link,origin,stem,pattern,created_at,updated_at,inflections from dpd_headwords where id = \"$1\" limit 1" | json

sqlite3 --batch local/dpd.db ".mode json" "select lemma_1,lemma_2,grammar,derived_from,neg,verb,trans,plus_case,non_ia,sanskrit,root_key,root_sign,root_base,family_root,family_word,family_compound,family_idioms,family_set,derivative,suffix,phonetic,source_1,stem,pattern,inflections, \
id, pos, construction, meaning_1, meaning_2, meaning_lit \
from dpd_headwords where id = \"$1\" limit 1" | json

