#!/bin/bash
DIR=`dirname $0`
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`
APP=$DIR/..
set -e

echo $SCRIPT: BEGIN `date`

npm version -ws --include-workspace-root --get-tag-version minor

### Publish EN
pushd dpd/en > /dev/null
echo $SCRIPT directory `pwd`
echo $SCRIPT: publishing `json name < ./package.json`
npm publish
popd > /dev/null

### Publish main
echo $SCRIPT directory `pwd`

echo $SCRIPT: updating ms-dpd dependencies
npm install --save @sc-voice/ms-dpd-en@latest
VER=`npm ls | head -1 | sed 's/.*@\([0-9.]*\).*/\1/'`

echo $SCRIPT: commit $VER
git commit -am "$VER"

echo $SCRIPT $VER

echo $SCRIPT: publishing `json name < ./package.json`
npm publish
npm ls

echo $SCRIPT: END `date`
