#!/bin/bash
DIR=`dirname $0`
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`
APP=$DIR/..
set -e

echo $SCRIPT: BEGIN `date`

npm version --workspaces --include-workspace-root minor

pushd dpd/en > /dev/null
pwd
echo $SCRIPT: publish `cat package.json | grep '"name"'
npm publish
popd > /dev/null

npm install --save @sc-voice/ms-dpd-en@latest
VER=`npm ls | head -1 | sed 's/.*@\([0-9.]*\).*/\1/'`
git commit -am "$VER"

echo $SCRIPT $VER

echo $SCRIPT: publish `cat package.json | grep '"name"'
npm publish
npm ls

echo $SCRIPT: END `date`
