#!/usr/bin/bash
DBNAME=dpd.db
TARNAME=$DBNAME.tar
BZ2NAME=$TARNAME.bz2
SCRIPT=`basename $0`
BZ2SRC=~/Downloads/$BZ2NAME

set -e
echo $SCRIPT '[BEGIN]' `date`
sync

echo $SCRIPT: "==> Download $BZ2NAME from digitalpalidictionary:"
echo $SCRIPT: "  https://bit.ly/dpd-releases"
echo $SCRIPT: "  === OR ==="
echo $SCRIPT: "  https://github.com/digitalpalidictionary/digitalpalidictionary/releases"
read -p "$SCRIPT: ==> Downloaded? (Y/n)" YN
if [[ "$YN" != "Y" && "$YN" != "y" && "$YN" != "" ]]; then 
  echo $SCRIPT: "[CANCELED]"
  exit -1
fi

read -p "$SCRIPT: ==> Downloaded file? ($BZ2SRC):" YN
if [ "$YN" != "" ]; then
  BZ2SRC=$YN
fi
echo "$SCRIPT:   $BZ2SRC"

type bzip2 >> /dev/null; RC=$? 
if [ "$RC" == "0" ]; then
  echo $SCRIPT: "bzip2 found (OK)"
else
  echo $SCRIPT: "bzip2 not found (installing...)"
  sudo apt install bzip2
fi

type sqlite3 >> /dev/null; RC=$?
if [ "$RC" == "0" ]; then
  echo $SCRIPT: "sqlite3 found (OK)"
else
  echo $SCRIPT: "sqlite3 not found (installing...)"
  sudo apt install sqlite3
fi

if [ ! -e $BZ2SRC ]; then
  echo $SCRIPT: "$BZ2SRC not found. Waiting..."
  sleep 8
fi
if [ ! -e $BZ2SRC ]; then
  echo $SCRIPT: "$BZ2SRC not found. Waiting..."
  sleep 13
fi
if [ ! -e $BZ2SRC ]; then
  echo $SCRIPT: "$BZ2SRC not found. Waiting..."
  sleep 21
fi
echo "$SCRIPT:"  `ls -l $BZ2SRC`
if [ -e $BZ2SRC ]; then
  echo $SCRIPT: "Moving $BZ2SRC to local/$BZ2NAME"
  mv -f $BZ2SRC local/$BZ2NAME
else
  echo $SCRIPT: "[FAIL] $BZ2SRC not found:"
  exit -1
fi

if [ -e local/$BZ2NAME ]; then
  echo $SCRIPT: "bzip2 -d local/$BZ2NAME (ETA ~10-20s...)"
  rm -f local/$TARNAME
  bzip2 -v -d local/$BZ2NAME
else 
  echo $SCRIPT: "[FAIL] local/$BZ2NAME not found..."
  exit -1
fi

if [ -e local/$TARNAME ]; then
  echo $SCRIPT: "tar xvf local/$TARNAME (...)"
  pushd local > /dev/null
  rm -f $DBNAME
  tar -xvf $TARNAME
  popd > /dev/null
  ls -l local/$DBNAME
else 
  echo $SCRIPT: "[FAIL] local/$TARNAME not found"
  exit -1
fi

OUTFILE=src/dpd-inflection-templates
echo $SCRIPT: "writing inflection templates to $OUTFILE"
sqlite3 local/dpd.db "select * from inflection_templates" > $OUTFILE
echo $SCRIPT: `ls -l $OUTFILE`

echo $SCRIPT: '[END:OK]' `date`
