#!/usr/bin/env node
var fs = require("fs");
var stdinBuffer = fs.readFileSync(0); // STDIN_FILENO = 0
let [ header, ...rows ] = stdinBuffer.toString().trim().split('\n')

let headers = header.split('|');
//console.log(headers);
let data = rows.reduce((ar,row,i)=>{
  if (row) {
    let vals = row.split('|');
    let json = vals.reduce((av,v,j)=>{
      if (v) {
        av[headers[j]] = v;
      }
      return av;
    },{});
    ar.push(json);
  }
  return ar;
}, []);
console.log(JSON.stringify(data, null, 2));
