export const DBG = {
  PALI: 0,
  DICTIONARY_CREATE: 0,
  ENTRY_OF: 0,
  EXPERIMENTAL: 0,
  FIND: 0,
  FIND_DEFINITION: 0,
  FIND_WORDS: 0,
  INFLECTION_FIND: 0,
  MATCHES_WORD: 0,
  SANKEY: 0,
  WORD_INFLECTIONS: 0,
}

